---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maestro-agent:agent
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maestro-agent:agent
subjects:
  - kind: ServiceAccount
    name: {{ include "maestro-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maestro-agent:execution-admin
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # We deploy a controller that could work with permission lower than cluster-admin, the tradeoff is
  # responsivity because list/watch cannot be maintained over too many namespaces.
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "maestro-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maestro-agent:execution
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maestro-agent:execution
subjects:
  - kind: ServiceAccount
    name: {{ include "maestro-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
