---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maestro-agent:agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maestro-agent:agent
subjects:
  - kind: ServiceAccount
    name: {{ include "maestro-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maestro-agent:agent:extension-apiserver
  namespace: kube-system
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maestro-agent:agent:extension-apiserver
subjects:
  - kind: ServiceAccount
    name: {{ include "maestro-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
