---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maestro-agent:agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
rules:
# leader election needs to operate configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "update", "watch", "patch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maestro-agent:agent:extension-apiserver
  namespace: kube-system
  labels:
    {{- include "maestro-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["extension-apiserver-authentication"]
  verbs: ["get", "list", "watch"]
