apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maestro-server.serviceAccountName" . }}
  labels:
    {{- include "maestro-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
